"""empty message

Revision ID: 047814a533cd
Revises: dc82e8d5f9ef
Create Date: 2019-09-03 19:18:09.805480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047814a533cd'
down_revision = 'dc82e8d5f9ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domain')
    # ### end Alembic commands ###
